#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -g3 -rdynamic -fPIC -DPURIFY -D_FORTIFY_SOURCE=2 -DBN_DEBUG -DREF_CHECK -DCONF_DEBUG -DCRYPTO_MDEBUG -m64 -DL_ENDIAN -DTERMIO -g -Wall"
  #define PLATFORM "debug-linux-x86_64"
  #define DATE "Tue Dec 23 02:08:17 EST 2014"
#endif
